# Application Configuration
app:
  name: go-chat-system
  version: 1.0.0
  environment: development # development, staging, production

# Database Configuration
database:
  host: localhost
  port: 5433
  user: chat-user
  password: chat-password
  name: chat-db
  sslmode: disable
  pool:
    max_connections: 25
    min_connections: 5
    max_conn_lifetime: 5m
    max_conn_idle_time: 1m
    health_check_period: 1m

# JWT Configuration
jwt:
  secret: super-secret
  expiry: 24h
  issuer: system

# Service Ports
server:
  port: 8002
  host: http://localhost

# Frontend Ports : "http://localhost:3000"
CORS:
  port: 3000
  host: http://localhost

# Logging Configuration
logging:
  level: info # debug, info, warn, error
  format: json # json or console
  output: stdout

# Redis
redis:
  host: localhost
  port: 6380
  password: ""
  db: 0
